from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.colors import HexColor
from io import BytesIO
import re

def generate_judicial_pdf(title, content):
    """
    Generates a professional, judicial-style PDF from HTML/Markdown-like content.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=A4,
        rightMargin=50, 
        leftMargin=50,
        topMargin=50, 
        bottomMargin=50
    )

    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'JudicialTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        textColor=HexColor('#0f172a'),
        alignment=1, # Center
        spaceAfter=20
    )

    heading_style = ParagraphStyle(
        'JudicialHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=16,
        textColor=HexColor('#d97706'),
        spaceBefore=15,
        spaceAfter=10
    )

    body_style = ParagraphStyle(
        'JudicialBody',
        parent=styles['Normal'],
        fontName='Times-Roman',
        fontSize=12,
        leading=16,
        alignment=4, # Justify
        spaceAfter=10
    )

    meta_style = ParagraphStyle(
        'JudicialMeta',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        textColor=HexColor('#64748b'),
        alignment=1
    )

    elements = []

    # Header / Logo Placeholder
    elements.append(Paragraph("LEGAIFY", title_style))
    elements.append(Paragraph("KSLU Academic Division - AI Study Companion", meta_style))
    elements.append(Spacer(1, 0.5 * inch))

    # Main Title
    elements.append(Paragraph(title, heading_style))
    elements.append(Spacer(1, 0.2 * inch))

    # Process Content (Very simple markdown parsing)
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        if line.startswith('### '):
            elements.append(Paragraph(line[4:], heading_style))
        elif line.startswith('## '):
            elements.append(Paragraph(line[3:], heading_style))
        elif line.startswith('# '):
            elements.append(Paragraph(line[2:], title_style))
        elif line.startswith('* ') or line.startswith('- '):
            elements.append(Paragraph(f"• {line[2:]}", body_style))
        else:
            # Handle bold text in markdown
            line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
            elements.append(Paragraph(line, body_style))

    # Footer
    elements.append(Spacer(1, 1 * inch))
    elements.append(Paragraph("--- End of Document ---", meta_style))
    elements.append(Paragraph("Generated by Legaify AI Core for KSLU students.", meta_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer
